routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('reset', 'ResetController@reset')->name('reset');

/** Admin */
Route::group(['middleware' => ['status','auth']],function (){
    $groupData = [
        'namespace' => 'Blog\Admin',
        'prefix' => 'admin',
    ];

    Route::group($groupData, function (){
        Route::resource('index','MainController')
            ->names('blog.admin.index');

        Route::resource('orders','OrderController')
            ->names('blog.admin.orders');
        Route::get('/orders/change/{id}','OrderController@change')
            ->name('blog.admin.orders.change');
        Route::post('/orders/save/{id}','OrderController@save')
            ->name('blog.admin.orders.save');
        Route::get('/orders/forcedestroy/{id}','OrderController@forcedestroy')
            ->name('blog.admin.orders.forcedestroy');

        Route::get('/categories/mydel','CategoryController@mydel')
            ->name('blog.admin.categories.mydel');
        Route::resource('catigories','CategoryController')
            ->names('blog.admin.categories');

        Route::resource('users','UserController')
            ->names('blog.admin.users');

        Route::get('/products/related','ProductController@related');
        Route::match(['get','post'],'/products/ajax-image-upload','ProductController@ajaxImage');
        Route::delete('/products/ajax-remove-image/{filename}','ProductController@deleteImage');

        Route::post('/products/gallery','ProductController@gallery')
            ->name('blog.admin.products.gallery');
        Route::post('/products/delete-gallery','ProductController@deleteGallery')
            ->name('blog.admin.products.deletegallery');

        Route::get('/products/return-status/{id}','ProductController@returnStatus')
            ->name('blog.admin.products.returnstatus');
        Route::get('/products/delete-status/{id}','ProductController@deleteStatus')
            ->name('blog.admin.products.deletestatus');
        Route::get('/products/delete-product/{id}','ProductController@deleteProduct')
            ->name('blog.admin.products.deleteproduct');
        

        Route::resource('products','ProductController')
            ->names('blog.admin.products');

        Route::get('/filter/group-filter','FilterController@attributeGroup');
        Route::match(['get','post'],'/filter/group-add','FilterController@addGroup');
        Route::match(['get','post'],'/filter/group-edit/{id}','FilterController@editGroup');
        Route::get('/filter/group-delete/{id}','FilterController@deleteGroup');
        Route::get('/filter/attributes-filter','FilterController@attributeFilter');
        Route::match(['get','post'],'/filter/attrs-add','FilterController@attributeAdd');
        Route::match(['get','post'],'/filter/attr-edit/{id}','FilterController@attributeEdit');
        Route::get('/filter/attr-delete/{id}','FilterController@attributeDelete');

        Route::get('/currency/index','CurrencyController@index');
        Route::match(['get','post'],'/currency/add','CurrencyController@add');
        Route::match(['get','post'],'/currency/edit/{id}','CurrencyController@edit');
        Route::get('/currency/delete/{id}','CurrencyController@delete');

        Route::get('/search/result','SearchController@index');
        Route::get('/autocomplete','SearchController@search');

    });
});

Route::get('user/index','Blog\User\MainController@index');

app/Models/Admin/Product.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $fillable = [
        'category_id',
        'brand_id',
        'title',
        'alias',
        'content',
        'price',
        'old_price',
        'status',
        'keywords',
        'description',
        'img',
        'hit',
    ];
}

app/Http/Controllers/Blog/Admin/ProductController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Http\Requests\AdminProductsRequest;
use App\Models\Admin\Category;
use App\Models\Admin\Product;
use App\Repositories\Admin\ProductRepository;
use App\SBlog\Core\BlogApp;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MetaTag;

class ProductController extends AdminBaseController
{
    private $productRepository;

    public function __construct()
    {
        parent::__construct();
        $this->productRepository = app(ProductRepository::class);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $perpage = 10;
        $getAllProducts = $this->productRepository->getAllProducts($perpage);
        $count = $this->productRepository->getCountProduct();

        MetaTag::setTags(['title' => "Список продуктов"]);
        return view('blog.admin.product.index', compact('getAllProducts', 'count'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $item = new Category();

        MetaTag::setTags(['title' => "Создание нового продукта"]);
        return view('blog.admin.product.create', [
            'catigories' => Category::with('children')
                ->where('parent_id', '0')
                ->get(),
            'delimiter' => '-',
            'item' => $item,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(AdminProductsRequest $request)
    {
        $data = $request->input();
        $product = (new Product())->create($data);
        $id = $product->id;
        $product->status = $request->status ? '1' : '0';
        $product->hit = $request->hit ? '1' : '0';
        $product->category_id = $request->parent_id ?? '0';
        $this->productRepository->getImg($product);
        $save = $product->save();
        if ($save) {
            $this->productRepository->editFilter($id, $data);
            $this->productRepository->editRelateProduct($id, $data);
            $this->productRepository->saveGallery($id);
            return redirect()
                ->route('blog.admin.products.create', [$product->id])
                ->with(['success' => "Успешно сохранено"]);
        } else {
            return back()
                ->withErrors(['msg' => "Ошибка сохранения"])
                ->withInput();
        }
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $product = $this->productRepository->getInfoProduct($id);
        $id = $product->id;
        BlogApp::get_instance()->setProperty('parent_id', $product->category_id);

        $filter = $this->productRepository->getFiltersProduct($id);
        $related_products = $this->productRepository->getRelatedProducts($id);
        $images = $this->productRepository->getGallery($id);

        MetaTag::setTags(['title' => "Редактирование продукта № $id"]);
        return view('blog.admin.product.edit', compact('product', 'filter', 'related_products', 'id', 'images'), [
            'catigories' => Category::with('children')
                ->where('parent_id', '0')
                ->get(),
            'delimiter' => '-',
            'product' => $product,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(AdminProductsRequest $request, $id)
    {
        $product = $this->productRepository->getId($id);
        if (empty($product)) {
            return back()
                ->withErrors(['msg' => "Запись = [{$id}] не найдена "])
                ->withInput();
        }
        $data = $request->all();
        $result = $product->update($data);
        $product->status = $request->status ? '1' : '0';
        $product->hit = $request->hit ? '1' : '0';
        $product->category_id = $request->parent_id ?? $product->category_id;
        $this->productRepository->getImg($product);
        $save = $product->save();

        if ($result && $save){
            $this->productRepository->editFilter($id,$data);
            $this->productRepository->editRelateProduct($id,$data);
            $this->productRepository->saveGallery($id);
            return redirect()
                ->route('blog.admin.products.edit',[$product->id])
                ->with(['success' => "Успешно сохранено"]);
        }else{
            return back()
                ->withErrors(['msg' => "Ошибка сохранения"])
                ->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function related(Request $request)
    {
        $q = isset($request->q) ? htmlspecialchars(trim($request->q)) : '';
        $data['items'] = [];
        $products = $this->productRepository->getProducts($q);
        if ($products) {
            $i = 0;
            foreach ($products as $id => $title) {
                $data['items'][$i]['id'] = $title->id;
                $data['items'][$i]['text'] = $title->title;
                $i++;
            }
        };
        echo json_encode($data);
        die;
    }

    public function ajaxImage(Request $request)
    {
        if ($request->isMethod('get')) {
            return view('blog.admin.product.include.image_single_edit');
        } else {
            $validator = \Validator::make($request->all(),
                [
                    'title' => 'image|max:1000',
                ],
                [
                    'file.image' => 'Файл должен быть картинкой (jpeg, phg, gif, or svg)',
                    'file.max' => 'Ошибка! Максимальный размер картинки - 5 мб',
                ]);
            if ($validator->fails()) {
                return array(
                    'fail' => true,
                    'errors' => $validator->errors(),
                );
            }

            $extension = $request->file('file')->getClientOriginalExtension();
            $dir = 'uploads/single/';
            $filename = uniqid() . '_' . date('dmYHi') . '.' . $extension;
            $request->file('file')->move($dir, $filename);
            $wmax = BlogApp::get_instance()->getProperty('img_width');
            $hmax = BlogApp::get_instance()->getProperty('img_height');
            $this->productRepository->uploadImg($filename, $wmax, $hmax);
            return $filename;
        }

    }

    public function gallery(Request $request)
    {
        //dd("ok->".$request);
        $validator = \Validator::make($request->all(),
            [
                'title' => 'image|max:5000',
            ],
            [
                'file.image' => 'Файл должен быть картинкой (jpeg, phg, gif, or svg)',
                'file.max' => 'Ошибка! Максимальный размер картинки - 5 мб',
            ]);
        if ($validator->fails()) {
            return array(
                'fail' => true,
                'errors' => $validator->errors(),
            );
        }

        if (isset($_GET['upload'])) {
            $wmax = BlogApp::get_instance()->getProperty('gallery_width');
            $hmax = BlogApp::get_instance()->getProperty('gallery_height');
            $name = $_POST['name'];
            $this->productRepository->uploadGallery($name, $wmax, $hmax);
        }

    }

    public function deleteImage($filename)
    {
        \File::delete('uploads/single/' . $filename);
    }

    public function deletegallery()
    {
        $id = isset($_POST['id']) ? $_POST['id'] : null;
        $src = isset($_POST['src']) ? $_POST['src'] : null;
        if (!$id || !$src) {
            return;
        }
        if (\DB::delete("DELETE FROM galleries WHERE product_id = ? AND img = ?", [$id, $src])) {
            @unlink("uploads/gallery/$src");
            exit('1');
        }
        return;
    }

    public function returnStatus($id)
    {
        if ($id){
            $st = $this->productRepository->returnStatus($id);
            if ($st){
                return redirect()
                    ->route('blog.admin.products.index')
                    ->with(['success' => "Успешно сохранено"]);
            }else{
                return back()
                    ->withErrors(['msg' => "Ошибка сохранения"])
                    ->withInput();
            }
        }
    }

    public function deleteStatus($id)
    {
        if ($id){
            $st = $this->productRepository->deleteStatusOne($id);
            if ($st){
                return redirect()
                    ->route('blog.admin.products.index')
                    ->with(['success' => "Успешно удалено"]);
            }else{
                return back()
                    ->withErrors(['msg' => "Ошибка удаления"])
                    ->withInput();
            }
        }
    }

    public function deleteProduct($id)
    {
        if ($id){
            $gal =$this->productRepository->deleteImgGalleryFromPath($id);
            $db = $this->productRepository->deleteFromDB($id);
            if ($db){
                return redirect()
                    ->route('blog.admin.products.index')
                    ->with(['success' => "Успешно удалено"]);
            }else{
                return back()
                    ->withErrors(['msg' => "Ошибка удаления"])
                    ->withInput();
            }

resources/views/blog/admin/product/create.blade.php
@extends('layouts.app_admin')

@section('content')
    <section class="content-header">
        @component('blog.admin.components.breadcrumb')
            @slot('title') Добавление нового товара @endslot
            @slot('parent') Главная @endslot
            @slot('product') Список товаров @endslot
            @slot('active') Новый товар @endslot
        @endcomponent
    </section>

    <!--    Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <form action="{{route('blog.admin.products.store',$item->id)}}" method="post"
                          data-toggle="validator" id="add">
                        @csrf

                        <div class="box-body">
                            <div class="form-group has-feedback">
                                <label for="title">Наименование товара</label>
                                <input type="text" name="title" class="form-control" id="title"
                                       placeholder="Наименование товара"
                                       value="{{old('title')}}" required>

                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                            <div class="form-group">
                                <select name="parent_id" id="parent_id" class="form-control" required>
                                    <option>--выберите категорию--</option>
                                    @include('blog.admin.product.include.edit_categories_all_list',['categories'=>$catigories])
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="keywords">Ключевые слова</label>
                                <input type="text" name="keywords" class="form-control" id="keywords"
                                       placeholder="Ключевые слова" value="{{old('keywords')}}">
                            </div>
                            <div class="form-group">
                                <label for="description">Описание</label>
                                <input type="text" name="description" class="form-control" id="description"
                                       placeholder="Описание" value="{{old('description')}}">
                            </div>
                            <div class="form-group">
                                <label for="price">Цена</label>
                                <input type="text" name="price" class="form-control" id="price"
                                       placeholder="Цена" pattern="^[0-9.]{1,}$" value="{{old('price')}}"
                                       required data-error="Допускаются цыфры и десятичная точка">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <label for="old_price">Старая цена</label>
                                <input type="text" name="old_price" class="form-control" id="price"
                                       placeholder="Старая цена" pattern="^[0-9.]{1,}$" value="{{old('old_price')}}"
                                       required data-error="Допускаются цыфры и десятичная точка">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group has-feedback">
                                <label for="content">Контент</label>
                                <textarea name="content" id="editor1" cols="80"rows="10">{{old('content')}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="status" checked> Статус
                                </label>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="hit"> Хит
                                </label>
                            </div>
                            <div class="form-group has-feedback">
                                <label for="related">Связанные товары</label>
                                <p><small>Начните вводить наименование товара...</small></p>
                                <select name="related[]"class="selected2 form-control" id="related" multiple>

                                </select>
                            </div>
                            <div class="form-group">
                                <label for="related">фильтры продукта</label>
                                {{Widget::run('filter',['tpl'=>'widgets.filter','filter' => null])}}
                            </div>

                            <div class="form-group">
                                <div class="col-md-4">
                                    @include('blog.admin.product.include.image_single_create')
                                </div>
                                <div class="col-md-8">
                                    @include('blog.admin.product.include.image_gallery_create')
                                </div>
                            </div>
                        </div>

                        <input type="hidden" id="_token" value="{{csrf_token()}}">

                        <div class="box-footer">
                            <button type="submit" class="btn btn-success">Добавить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>

@endsection

resources/views/blog/admin/product/edit.blade.php
@extends('layouts.app_admin')

@section('content')
    <section class="content-header">
        @component('blog.admin.components.breadcrumb')
            @slot('title') Редактирование продукта @endslot
            @slot('parent') Главная @endslot
            @slot('product') Список продуктов {{$product->title}}@endslot
            @slot('active') Редактирование продукта @endslot
        @endcomponent
    </section>

    <!--    Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <form action="{{route('blog.admin.products.update',$product->id)}}" method="post"
                          data-toggle="validator" id="add">
                        @method('PATCH')
                        @csrf

                        <div class="box-body">
                            <div class="form-group has-feedback">
                                <label for="title">Наименование товара</label>
                                <input type="text" name="title" class="form-control" id="title"
                                       placeholder="Наименование товара"
                                       value="{{$product->title}}" required>

                                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
                            </div>
                            <div class="form-group">
                                <label for="title">Категория товара</label>
                                <select name="parent_id" id="parent_id" class="form-control" required>
                                    <option disabled>--выберите категорию--</option>
                                    @include('blog.admin.product.include.categories_for_prod',['categories'=>$catigories])
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="keywords">Ключевые слова</label>
                                <input type="text" name="keywords" class="form-control" id="keywords"
                                       placeholder="Ключевые слова" value="{{$product->keywords}}">
                            </div>
                            <div class="form-group">
                                <label for="description">Описание</label>
                                <input type="text" name="description" class="form-control" id="description"
                                       placeholder="Описание" value="{{$product->description}}">
                            </div>
                            <div class="form-group">
                                <label for="price">Цена</label>
                                <input type="text" name="price" class="form-control" id="price"
                                       placeholder="Цена" pattern="^[0-9.]{1,}$" value="{{$product->price}}"
                                       required data-error="Допускаются цыфры и десятичная точка">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <label for="old_price">Старая цена</label>
                                <input type="text" name="old_price" class="form-control" id="price"
                                       placeholder="Старая цена" pattern="^[0-9.]{1,}$" value="{{$product->old_price}}"
                                       required data-error="Допускаются цыфры и десятичная точка">
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group has-feedback">
                                <label for="content">Контент</label>
                                <textarea name="content" id="editor1" cols="80"rows="10">{{$product->content}}</textarea>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="status" {{$product->hit ? 'checked':null}}> Статус
                                </label>
                            </div>
                            <div class="form-group">
                                <label>
                                    <input type="checkbox" name="hit" {{$product->status ? 'checked':null}}> Хит
                                </label>
                            </div>
                            <div class="form-group has-feedback">
                                <label for="related">Связанные товары</label>
                                <p><small>Начните вводить наименование товара...</small></p>
                                <select name="related[]"class="selected2 form-control" id="related" multiple>

                                    @if(!empty($related_products))
                                        @foreach($related_products as $prod)
                                            <option value="{{$prod->related_id}}" selected>
                                                {{$prod->title}}
                                            </option>
                                        @endforeach
                                    @endif
                                </select>
                            </div>
                            <div class="form-group">
                                <label for="related">фильтры продукта</label>
                                {{Widget::run('filter',['tpl'=>'widgets.filter','filter' => $filter,])}}
                            </div>

                            <div class="form-group">
                                <div class="col-md-4">
                                    @include('blog.admin.product.include.image_single_edit')
                                </div>
                                <div class="col-md-8">
                                    @include('blog.admin.product.include.image_gallery_edit')
                                </div>
                            </div>
                        </div>

                        <input type="hidden" id="_token" value="{{csrf_token()}}">

                        <div class="box-footer">
                            <button type="submit" class="btn btn-success">Сохранить</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </section>
    <div class="hidden" data-name = "{{$id}}">

    </div>
@endsection

resources/views/blog/admin/product/index.blade.php
@extends('layouts.app_admin')

@section('content')
    <section class="content-header">
        @component('blog.admin.components.breadcrumb')
            @slot('title') Список товаров @endslot
            @slot('parent') Главная @endslot
            @slot('active') Список товаров @endslot
        @endcomponent
    </section>

    <!--    Main content -->
    <section class="content">
        <div class="row">
            <div class="col-md-12">
                <div class="box">
                    <div class="box-body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                <tr>
                                    <th>ID</th>
                                    <th>Категории</th>
                                    <th>Наименование</th>
                                    <th>Цена</th>
                                    <th>Статус</th>
                                    <th>Действия</th>
                                </tr>
                                </thead>
                                <tbody>
                                @forelse($getAllProducts as $product)
                                    <tr @if($product->status == 0) style="font-weight: bold" ; @endif>
                                        <td>{{$product->id}}</td>
                                        <td>{{$product->cat}}</td>
                                        <td>{{$product->title}}</td>
                                        <td>{{$product->price}}</td>
                                        <td>{{$product->status ? 'On':'Off'}}</td>
                                        <td>
                                            <a href="{{route('blog.admin.products.edit',$product->id)}}"
                                               title="Редактировать">
                                                <i class="fa fa-fw fa-eye"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                            @if($product->status == 0)
                                                <a href="{{route('blog.admin.products.returnstatus',$product->id)}}"
                                                   class="delete" title="Перевести статус = On">
                                                    <i class="fa fa-fw fa-refresh"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                            @else
                                                <a href="{{route('blog.admin.products.deletestatus',$product->id)}}"
                                                   class="delete" title="Перевести статус = Off">
                                                    <i class="fa fa-fw fa-close"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;
                                            @endif
{{--                                            {{route('blog.admin.products.deleteproduct',$product->id)}}--}}
                                            @if($product)
                                                <a href="{{route('blog.admin.products.deleteproduct',$product->id)}}"
                                                   class="delete" title="Удалить из БД">
                                                    <i class="fa fa-fw fa-close text-danger"></i></a>
                                            @endif
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td class="text-center" colspan="3"><h2>Заказов нет</h2></td>
                                    </tr>
                                @endforelse
                                </tbody>
                            </table>
                        </div>
                        <div class="text-center">
                            <p>{{count($getAllProducts)}} заказа(ов) из {{$count}}</p>

                            @if($getAllProducts->total() > $getAllProducts->count())
                                <br>
                                <div class="row justify-content-center">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-body">
                                                {{$getAllProducts->links()}}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            @endif

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

@endsection