routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::get('reset', 'ResetController@reset')->name('reset');

/** Admin */
Route::group(['middleware' => ['status','auth']],function (){
    $groupData = [
        'namespace' => 'Blog\Admin',
        'prefix' => 'admin',
    ];

    Route::group($groupData, function (){
        Route::resource('index','MainController')
            ->names('blog.admin.index');

        Route::resource('orders','OrderController')
            ->names('blog.admin.orders');
        Route::get('/orders/change/{id}','OrderController@change')
            ->name('blog.admin.orders.change');
        Route::post('/orders/save/{id}','OrderController@save')
            ->name('blog.admin.orders.save');
        Route::get('/orders/forcedestroy/{id}','OrderController@forcedestroy')
            ->name('blog.admin.orders.forcedestroy');

        Route::get('/categories/mydel','CategoryController@mydel')
            ->name('blog.admin.categories.mydel');
        Route::resource('catigories','CategoryController')
            ->names('blog.admin.categories');

        Route::resource('users','UserController')
            ->names('blog.admin.users');

        Route::get('/products/related','ProductController@related');
        Route::match(['get','post'],'/products/ajax-image-upload','ProductController@ajaxImage');
        Route::delete('/products/ajax-remove-image/{filename}','ProductController@deleteImage');

        Route::post('/products/gallery','ProductController@gallery')
            ->name('blog.admin.products.gallery');
        Route::post('/products/delete-gallery','ProductController@deleteGallery')
            ->name('blog.admin.products.deletegallery');

        Route::get('/products/return-status/{id}','ProductController@returnStatus')
            ->name('blog.admin.products.returnstatus');
        Route::get('/products/delete-status/{id}','ProductController@deleteStatus')
            ->name('blog.admin.products.deletestatus');
        Route::get('/products/delete-product/{id}','ProductController@deleteProduct')
            ->name('blog.admin.products.deleteproduct');
        

        Route::resource('products','ProductController')
            ->names('blog.admin.products');

        Route::get('/filter/group-filter','FilterController@attributeGroup');
        Route::match(['get','post'],'/filter/group-add','FilterController@addGroup');
        Route::match(['get','post'],'/filter/group-edit/{id}','FilterController@editGroup');
        Route::get('/filter/group-delete/{id}','FilterController@deleteGroup');
        Route::get('/filter/attributes-filter','FilterController@attributeFilter');
        Route::match(['get','post'],'/filter/attrs-add','FilterController@attributeAdd');
        Route::match(['get','post'],'/filter/attr-edit/{id}','FilterController@attributeEdit');
        Route::get('/filter/attr-delete/{id}','FilterController@attributeDelete');

        Route::get('/currency/index','CurrencyController@index');
        Route::match(['get','post'],'/currency/add','CurrencyController@add');
        Route::match(['get','post'],'/currency/edit/{id}','CurrencyController@edit');
        Route::get('/currency/delete/{id}','CurrencyController@delete');

        Route::get('/search/result','SearchController@index');
        Route::get('/autocomplete','SearchController@search');

    });
});

Route::get('user/index','Blog\User\MainController@index');

app/Http/Controllers/Blog/Admin/MainController.php
<?php

namespace App\Http\Controllers\Blog\Admin;

use App\Repositories\Admin\MainRepository;
use App\Repositories\Admin\OrderRepository;
use App\Repositories\Admin\ProductRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use MetaTag;

class MainController extends AdminBaseController
{
    private $orderRepository;
    private $productRepository;

    public function __construct()
    {
        parent::__construct();
        $this->orderRepository = app(OrderRepository::class);
        $this->productRepository = app(ProductRepository::class);
    }

    public function index(){
        $countOrders = MainRepository::getCountOrders();
        $countUsers = MainRepository::getCountUsers();
        $countProducts = MainRepository::getCountProducts();
        $countCategories = MainRepository::getCountCategories();

        $perpage = 4;

        $last_orders = $this->orderRepository->getAllOrders(7);
        $last_products = $this->productRepository->getLastProduct($perpage);

        MetaTag::setTags(['title' => 'Админ панель']);
        return view('blog.admin.main.index', compact('countOrders','countUsers',
            'countProducts','countCategories','last_products','last_orders'));
    }
}

app/Http/Controllers/Blog/Disabled/MainController.php
<?php

namespace App\Http\Controllers\Blog\Disabled;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MainController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('blog.disabled.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Blog/User/MainController.php
<?php

namespace App\Http\Controllers\Blog\User;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MainController extends Controller
{

    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('blog.user.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/blog/admin/main/include/orders.blade.php
<!-- TABLE: LATEST ORDERS -->
<div class="col-md-6">
<div class="box box-info">
    <div class="box-header with-border">
        <h3 class="box-title">Последние заказы</h3>

        <div class="box-tools pull-right">
            <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
            <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
        </div>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
        <div class="table-responsive">
            <table class="table no-margin">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>Покупатель</th>
                    <th>Статус</th>
                    <th>Сумма</th>
                </tr>
                </thead>
                <tbody>
                @foreach($last_orders as $order)
                    <tr>
                        <td><a href="{{route('blog.admin.orders.edit',$order->id)}}">{{$order->id}}</a></td>
                        <td><a href="{{route('blog.admin.orders.edit',$order->id)}}">{{ucfirst($order->name)}}</a></td>
                        <td><span class="label label-success">
                                @if($order->status == 0)Новый @endif
                                @if($order->status == 1)Завершен @endif
                                @if($order->status == 2)<b style="color: red">Удален</b> @endif
                            </span></td>
                        <td>
                            <div class="sparkbar" data-fgColor="#00a65a"data-height="20">{{$order->sum}}</div>
                        </td>
                    </tr>
                @endforeach
                </tbody>
            </table>
        </div>
        <!-- /.table-responsive -->
    </div>

    <!-- /.box-body -->
    <div class="box-footer clearfix">
        <a href="{{route('blog.admin.orders.index')}}" class="btn btn-sm btn-info btn-flat pull-left">Все заказы</a>
    </div>
</div>
</div>

resources/views/blog/admin/main/include/recentry.blade.php
<div class="col-md-6">
    <!-- PRODUCT LIST -->
    <div class="box box-primary">
        <div class="box-header with-border">
            <h3 class="box-title">Последние добавленые продукты</h3>
            <div class="box-tools pull-right">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button type="button" class="btn btn-box-tool" data-widget="remove"><i class="fa fa-times"></i></button>
            </div>
        </div>
        <div class="box-body">
            <ul class="products-list product-list-in-box">
                @foreach($last_products as $product)
                    <li class="item">
                        <div class="product-img">
                            @if(!empty($product->img))
                                <img src="{{asset('uploads/single/'.$product->img)}}" alt="image">
                            @else
                                <img src="{{asset('images/no_image.png')}}" alt="image">
                            @endif
                        </div>
                        <div class="product-info">
                            <a href="{{route('blog.admin.products.edit',$product->id)}}" class="product-title">{{$product->title}}
                            <span class="label label-warning pull-right">{{$product->price}}</span> </a>
                            <span class="product-description">{{$product->description}}</span>
                        </div>
                    </li>
                @endforeach
            </ul>
        </div>

        <div class="box-footer clearfix">
            <a href="" class="btn btn-sm btn-info btn-flat pull-left">Все продукты</a>
        </div>
    </div>
</div>